// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Custom_DA_FIR3\da_fir_bandpass.v
// Created: 2026-07-04 18:58:58
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: da_fir_bandpass
// Source Path: Custom_DA_FIR3/da_fir_bandpass
// Hierarchy Level: 0
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module da_fir_bandpass
          (clk,
           reset,
           clk_enable,
           In1,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] In1;  // sfix16_En15
  output  ce_out;
  output  signed [21:0] Out1;  // sfix22_En15


  wire enb;
  reg signed [15:0] Delay_1_out1;  // sfix16_En15
  reg signed [15:0] Delay_2_out1;  // sfix16_En15
  reg signed [15:0] Delay_3_out1;  // sfix16_En15
  reg signed [15:0] Delay_4_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_33_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_33_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_33_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_34_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_34_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_34_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_17_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_17_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_17_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_35_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_35_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_35_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_36_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_36_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_36_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_18_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_18_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_18_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_9_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_9_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_9_out1;  // sfix18_En15
  wire [3:0] BitSlice_Chunk_37_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_37_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_37_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_38_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_38_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_38_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_19_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_19_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_19_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_39_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_39_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_39_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_40_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_40_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_40_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_20_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_20_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_20_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_10_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_10_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_10_out1;  // sfix18_En15
  wire signed [18:0] Adder_S3_5_add_cast;  // sfix19_En15
  wire signed [18:0] Adder_S3_5_add_cast_1;  // sfix19_En15
  wire signed [18:0] Adder_S3_5_out1;  // sfix19_En15
  wire signed [15:0] ConstZero_S4_3_out1;  // sfix16_En15
  wire signed [19:0] Adder_S4_3_add_cast;  // sfix20_En15
  wire signed [19:0] Adder_S4_3_add_cast_1;  // sfix20_En15
  wire signed [19:0] Adder_S4_3_out1;  // sfix20_En15
  wire [3:0] BitSlice_Chunk_1_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_1_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_1_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_2_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_2_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_2_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_1_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_1_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_1_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_3_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_3_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_3_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_4_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_4_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_4_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_2_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_2_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_2_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_1_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_1_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_1_out1;  // sfix18_En15
  wire [3:0] BitSlice_Chunk_5_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_5_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_5_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_6_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_6_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_6_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_3_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_3_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_3_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_7_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_7_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_7_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_8_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_8_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_8_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_4_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_4_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_4_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_2_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_2_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_2_out1;  // sfix18_En15
  wire signed [18:0] Adder_S3_1_add_cast;  // sfix19_En15
  wire signed [18:0] Adder_S3_1_add_cast_1;  // sfix19_En15
  wire signed [18:0] Adder_S3_1_out1;  // sfix19_En15
  wire [3:0] BitSlice_Chunk_9_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_9_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_9_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_10_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_10_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_10_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_5_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_5_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_5_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_11_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_11_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_11_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_12_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_12_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_12_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_6_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_6_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_6_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_3_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_3_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_3_out1;  // sfix18_En15
  wire [3:0] BitSlice_Chunk_13_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_13_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_13_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_14_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_14_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_14_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_7_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_7_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_7_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_15_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_15_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_15_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_16_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_16_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_16_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_8_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_8_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_8_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_4_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_4_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_4_out1;  // sfix18_En15
  wire signed [18:0] Adder_S3_2_add_cast;  // sfix19_En15
  wire signed [18:0] Adder_S3_2_add_cast_1;  // sfix19_En15
  wire signed [18:0] Adder_S3_2_out1;  // sfix19_En15
  wire signed [19:0] Adder_S4_1_add_cast;  // sfix20_En15
  wire signed [19:0] Adder_S4_1_add_cast_1;  // sfix20_En15
  wire signed [19:0] Adder_S4_1_out1;  // sfix20_En15
  wire [3:0] BitSlice_Chunk_17_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_17_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_17_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_18_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_18_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_18_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_9_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_9_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_9_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_19_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_19_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_19_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_20_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_20_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_20_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_10_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_10_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_10_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_5_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_5_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_5_out1;  // sfix18_En15
  wire [3:0] BitSlice_Chunk_21_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_21_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_21_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_22_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_22_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_22_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_11_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_11_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_11_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_23_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_23_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_23_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_24_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_24_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_24_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_12_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_12_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_12_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_6_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_6_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_6_out1;  // sfix18_En15
  wire signed [18:0] Adder_S3_3_add_cast;  // sfix19_En15
  wire signed [18:0] Adder_S3_3_add_cast_1;  // sfix19_En15
  wire signed [18:0] Adder_S3_3_out1;  // sfix19_En15
  wire [3:0] BitSlice_Chunk_25_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_25_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_25_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_26_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_26_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_26_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_13_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_13_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_13_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_27_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_27_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_27_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_28_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_28_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_28_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_14_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_14_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_14_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_7_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_7_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_7_out1;  // sfix18_En15
  wire [3:0] BitSlice_Chunk_29_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_29_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_29_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_30_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_30_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_30_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_15_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_15_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_15_out1;  // sfix17_En15
  wire [3:0] BitSlice_Chunk_31_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_31_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_31_out1;  // sfix16_En15
  wire [3:0] BitSlice_Chunk_32_out1;  // ufix4
  wire signed [15:0] LUT_Chunk_32_1 [0:15];  // sfix16_En15 [16]
  wire signed [15:0] LUT_Chunk_32_out1;  // sfix16_En15
  wire signed [16:0] Adder_S1_16_add_cast;  // sfix17_En15
  wire signed [16:0] Adder_S1_16_add_cast_1;  // sfix17_En15
  wire signed [16:0] Adder_S1_16_out1;  // sfix17_En15
  wire signed [17:0] Adder_S2_8_add_cast;  // sfix18_En15
  wire signed [17:0] Adder_S2_8_add_cast_1;  // sfix18_En15
  wire signed [17:0] Adder_S2_8_out1;  // sfix18_En15
  wire signed [18:0] Adder_S3_4_add_cast;  // sfix19_En15
  wire signed [18:0] Adder_S3_4_add_cast_1;  // sfix19_En15
  wire signed [18:0] Adder_S3_4_out1;  // sfix19_En15
  wire signed [19:0] Adder_S4_2_add_cast;  // sfix20_En15
  wire signed [19:0] Adder_S4_2_add_cast_1;  // sfix20_En15
  wire signed [19:0] Adder_S4_2_out1;  // sfix20_En15
  wire signed [20:0] Adder_S5_1_add_cast;  // sfix21_En15
  wire signed [20:0] Adder_S5_1_add_cast_1;  // sfix21_En15
  wire signed [20:0] Adder_S5_1_out1;  // sfix21_En15
  wire signed [15:0] ConstZero_S5_2_out1;  // sfix16_En15
  wire signed [20:0] Adder_S5_2_add_cast;  // sfix21_En15
  wire signed [20:0] Adder_S5_2_add_cast_1;  // sfix21_En15
  wire signed [20:0] Adder_S5_2_out1;  // sfix21_En15
  wire signed [21:0] Adder_S6_1_add_cast;  // sfix22_En15
  wire signed [21:0] Adder_S6_1_add_cast_1;  // sfix22_En15
  wire signed [21:0] Adder_S6_1_out1;  // sfix22_En15
  wire signed [21:0] Shift_Arithmetic_Scale_out1;  // sfix22_En15


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Delay_1_process
      if (reset == 1'b1) begin
        Delay_1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_1_out1 <= In1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay_2_process
      if (reset == 1'b1) begin
        Delay_2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_2_out1 <= Delay_1_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay_3_process
      if (reset == 1'b1) begin
        Delay_3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_3_out1 <= Delay_2_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay_4_process
      if (reset == 1'b1) begin
        Delay_4_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_4_out1 <= Delay_3_out1;
        end
      end
    end



  assign BitSlice_Chunk_33_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_33_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_33_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_33_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_33_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_33_out1 = LUT_Chunk_33_1[BitSlice_Chunk_33_out1];



  assign BitSlice_Chunk_34_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_34_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_34_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_34_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_34_out1 = LUT_Chunk_34_1[BitSlice_Chunk_34_out1];



  assign Adder_S1_17_add_cast = {LUT_Chunk_33_out1[15], LUT_Chunk_33_out1};
  assign Adder_S1_17_add_cast_1 = {LUT_Chunk_34_out1[15], LUT_Chunk_34_out1};
  assign Adder_S1_17_out1 = Adder_S1_17_add_cast + Adder_S1_17_add_cast_1;



  assign BitSlice_Chunk_35_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_35_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_35_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_35_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_35_out1 = LUT_Chunk_35_1[BitSlice_Chunk_35_out1];



  assign BitSlice_Chunk_36_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_36_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_36_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_36_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_36_out1 = LUT_Chunk_36_1[BitSlice_Chunk_36_out1];



  assign Adder_S1_18_add_cast = {LUT_Chunk_35_out1[15], LUT_Chunk_35_out1};
  assign Adder_S1_18_add_cast_1 = {LUT_Chunk_36_out1[15], LUT_Chunk_36_out1};
  assign Adder_S1_18_out1 = Adder_S1_18_add_cast + Adder_S1_18_add_cast_1;



  assign Adder_S2_9_add_cast = {Adder_S1_17_out1[16], Adder_S1_17_out1};
  assign Adder_S2_9_add_cast_1 = {Adder_S1_18_out1[16], Adder_S1_18_out1};
  assign Adder_S2_9_out1 = Adder_S2_9_add_cast + Adder_S2_9_add_cast_1;



  assign BitSlice_Chunk_37_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_37_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_37_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_37_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_37_out1 = LUT_Chunk_37_1[BitSlice_Chunk_37_out1];



  assign BitSlice_Chunk_38_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_38_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_38_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_38_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_38_out1 = LUT_Chunk_38_1[BitSlice_Chunk_38_out1];



  assign Adder_S1_19_add_cast = {LUT_Chunk_37_out1[15], LUT_Chunk_37_out1};
  assign Adder_S1_19_add_cast_1 = {LUT_Chunk_38_out1[15], LUT_Chunk_38_out1};
  assign Adder_S1_19_out1 = Adder_S1_19_add_cast + Adder_S1_19_add_cast_1;



  assign BitSlice_Chunk_39_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_39_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_39_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_39_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_39_out1 = LUT_Chunk_39_1[BitSlice_Chunk_39_out1];



  assign BitSlice_Chunk_40_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_40_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[2] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[4] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[6] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[8] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[10] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[12] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_40_1[14] = 16'sb0000000000000000;
  assign LUT_Chunk_40_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_40_out1 = LUT_Chunk_40_1[BitSlice_Chunk_40_out1];



  assign Adder_S1_20_add_cast = {LUT_Chunk_39_out1[15], LUT_Chunk_39_out1};
  assign Adder_S1_20_add_cast_1 = {LUT_Chunk_40_out1[15], LUT_Chunk_40_out1};
  assign Adder_S1_20_out1 = Adder_S1_20_add_cast + Adder_S1_20_add_cast_1;



  assign Adder_S2_10_add_cast = {Adder_S1_19_out1[16], Adder_S1_19_out1};
  assign Adder_S2_10_add_cast_1 = {Adder_S1_20_out1[16], Adder_S1_20_out1};
  assign Adder_S2_10_out1 = Adder_S2_10_add_cast + Adder_S2_10_add_cast_1;



  assign Adder_S3_5_add_cast = {Adder_S2_9_out1[17], Adder_S2_9_out1};
  assign Adder_S3_5_add_cast_1 = {Adder_S2_10_out1[17], Adder_S2_10_out1};
  assign Adder_S3_5_out1 = Adder_S3_5_add_cast + Adder_S3_5_add_cast_1;



  assign ConstZero_S4_3_out1 = 16'sb0000000000000000;



  assign Adder_S4_3_add_cast = {Adder_S3_5_out1[18], Adder_S3_5_out1};
  assign Adder_S4_3_add_cast_1 = {{4{ConstZero_S4_3_out1[15]}}, ConstZero_S4_3_out1};
  assign Adder_S4_3_out1 = Adder_S4_3_add_cast + Adder_S4_3_add_cast_1;



  assign BitSlice_Chunk_1_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_1_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_1_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_1_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_1_out1 = LUT_Chunk_1_1[BitSlice_Chunk_1_out1];



  assign BitSlice_Chunk_2_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_2_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_2_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_2_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_2_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_2_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_2_out1 = LUT_Chunk_2_1[BitSlice_Chunk_2_out1];



  assign Adder_S1_1_add_cast = {LUT_Chunk_1_out1[15], LUT_Chunk_1_out1};
  assign Adder_S1_1_add_cast_1 = {LUT_Chunk_2_out1[15], LUT_Chunk_2_out1};
  assign Adder_S1_1_out1 = Adder_S1_1_add_cast + Adder_S1_1_add_cast_1;



  assign BitSlice_Chunk_3_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_3_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_3_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_3_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_3_out1 = LUT_Chunk_3_1[BitSlice_Chunk_3_out1];



  assign BitSlice_Chunk_4_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_4_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_4_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_4_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_4_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_4_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_4_out1 = LUT_Chunk_4_1[BitSlice_Chunk_4_out1];



  assign Adder_S1_2_add_cast = {LUT_Chunk_3_out1[15], LUT_Chunk_3_out1};
  assign Adder_S1_2_add_cast_1 = {LUT_Chunk_4_out1[15], LUT_Chunk_4_out1};
  assign Adder_S1_2_out1 = Adder_S1_2_add_cast + Adder_S1_2_add_cast_1;



  assign Adder_S2_1_add_cast = {Adder_S1_1_out1[16], Adder_S1_1_out1};
  assign Adder_S2_1_add_cast_1 = {Adder_S1_2_out1[16], Adder_S1_2_out1};
  assign Adder_S2_1_out1 = Adder_S2_1_add_cast + Adder_S2_1_add_cast_1;



  assign BitSlice_Chunk_5_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_5_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_5_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_5_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_5_out1 = LUT_Chunk_5_1[BitSlice_Chunk_5_out1];



  assign BitSlice_Chunk_6_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_6_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_6_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_6_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_6_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_6_out1 = LUT_Chunk_6_1[BitSlice_Chunk_6_out1];



  assign Adder_S1_3_add_cast = {LUT_Chunk_5_out1[15], LUT_Chunk_5_out1};
  assign Adder_S1_3_add_cast_1 = {LUT_Chunk_6_out1[15], LUT_Chunk_6_out1};
  assign Adder_S1_3_out1 = Adder_S1_3_add_cast + Adder_S1_3_add_cast_1;



  assign BitSlice_Chunk_7_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_7_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_7_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_7_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_7_out1 = LUT_Chunk_7_1[BitSlice_Chunk_7_out1];



  assign BitSlice_Chunk_8_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_8_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_8_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_8_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_8_out1 = LUT_Chunk_8_1[BitSlice_Chunk_8_out1];



  assign Adder_S1_4_add_cast = {LUT_Chunk_7_out1[15], LUT_Chunk_7_out1};
  assign Adder_S1_4_add_cast_1 = {LUT_Chunk_8_out1[15], LUT_Chunk_8_out1};
  assign Adder_S1_4_out1 = Adder_S1_4_add_cast + Adder_S1_4_add_cast_1;



  assign Adder_S2_2_add_cast = {Adder_S1_3_out1[16], Adder_S1_3_out1};
  assign Adder_S2_2_add_cast_1 = {Adder_S1_4_out1[16], Adder_S1_4_out1};
  assign Adder_S2_2_out1 = Adder_S2_2_add_cast + Adder_S2_2_add_cast_1;



  assign Adder_S3_1_add_cast = {Adder_S2_1_out1[17], Adder_S2_1_out1};
  assign Adder_S3_1_add_cast_1 = {Adder_S2_2_out1[17], Adder_S2_2_out1};
  assign Adder_S3_1_out1 = Adder_S3_1_add_cast + Adder_S3_1_add_cast_1;



  assign BitSlice_Chunk_9_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_9_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_9_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_9_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_9_out1 = LUT_Chunk_9_1[BitSlice_Chunk_9_out1];



  assign BitSlice_Chunk_10_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_10_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_10_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_10_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_10_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_10_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_10_out1 = LUT_Chunk_10_1[BitSlice_Chunk_10_out1];



  assign Adder_S1_5_add_cast = {LUT_Chunk_9_out1[15], LUT_Chunk_9_out1};
  assign Adder_S1_5_add_cast_1 = {LUT_Chunk_10_out1[15], LUT_Chunk_10_out1};
  assign Adder_S1_5_out1 = Adder_S1_5_add_cast + Adder_S1_5_add_cast_1;



  assign BitSlice_Chunk_11_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_11_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_11_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_11_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_11_out1 = LUT_Chunk_11_1[BitSlice_Chunk_11_out1];



  assign BitSlice_Chunk_12_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_12_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_12_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_12_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_12_out1 = LUT_Chunk_12_1[BitSlice_Chunk_12_out1];



  assign Adder_S1_6_add_cast = {LUT_Chunk_11_out1[15], LUT_Chunk_11_out1};
  assign Adder_S1_6_add_cast_1 = {LUT_Chunk_12_out1[15], LUT_Chunk_12_out1};
  assign Adder_S1_6_out1 = Adder_S1_6_add_cast + Adder_S1_6_add_cast_1;



  assign Adder_S2_3_add_cast = {Adder_S1_5_out1[16], Adder_S1_5_out1};
  assign Adder_S2_3_add_cast_1 = {Adder_S1_6_out1[16], Adder_S1_6_out1};
  assign Adder_S2_3_out1 = Adder_S2_3_add_cast + Adder_S2_3_add_cast_1;



  assign BitSlice_Chunk_13_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_13_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_13_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_13_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_13_out1 = LUT_Chunk_13_1[BitSlice_Chunk_13_out1];



  assign BitSlice_Chunk_14_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_14_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_14_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_14_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_14_out1 = LUT_Chunk_14_1[BitSlice_Chunk_14_out1];



  assign Adder_S1_7_add_cast = {LUT_Chunk_13_out1[15], LUT_Chunk_13_out1};
  assign Adder_S1_7_add_cast_1 = {LUT_Chunk_14_out1[15], LUT_Chunk_14_out1};
  assign Adder_S1_7_out1 = Adder_S1_7_add_cast + Adder_S1_7_add_cast_1;



  assign BitSlice_Chunk_15_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_15_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_15_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_15_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_15_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_15_out1 = LUT_Chunk_15_1[BitSlice_Chunk_15_out1];



  assign BitSlice_Chunk_16_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_16_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_16_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_16_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_16_out1 = LUT_Chunk_16_1[BitSlice_Chunk_16_out1];



  assign Adder_S1_8_add_cast = {LUT_Chunk_15_out1[15], LUT_Chunk_15_out1};
  assign Adder_S1_8_add_cast_1 = {LUT_Chunk_16_out1[15], LUT_Chunk_16_out1};
  assign Adder_S1_8_out1 = Adder_S1_8_add_cast + Adder_S1_8_add_cast_1;



  assign Adder_S2_4_add_cast = {Adder_S1_7_out1[16], Adder_S1_7_out1};
  assign Adder_S2_4_add_cast_1 = {Adder_S1_8_out1[16], Adder_S1_8_out1};
  assign Adder_S2_4_out1 = Adder_S2_4_add_cast + Adder_S2_4_add_cast_1;



  assign Adder_S3_2_add_cast = {Adder_S2_3_out1[17], Adder_S2_3_out1};
  assign Adder_S3_2_add_cast_1 = {Adder_S2_4_out1[17], Adder_S2_4_out1};
  assign Adder_S3_2_out1 = Adder_S3_2_add_cast + Adder_S3_2_add_cast_1;



  assign Adder_S4_1_add_cast = {Adder_S3_1_out1[18], Adder_S3_1_out1};
  assign Adder_S4_1_add_cast_1 = {Adder_S3_2_out1[18], Adder_S3_2_out1};
  assign Adder_S4_1_out1 = Adder_S4_1_add_cast + Adder_S4_1_add_cast_1;



  assign BitSlice_Chunk_17_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_17_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_17_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_17_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_17_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_17_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_17_out1 = LUT_Chunk_17_1[BitSlice_Chunk_17_out1];



  assign BitSlice_Chunk_18_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_18_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_18_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_18_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_18_out1 = LUT_Chunk_18_1[BitSlice_Chunk_18_out1];



  assign Adder_S1_9_add_cast = {LUT_Chunk_17_out1[15], LUT_Chunk_17_out1};
  assign Adder_S1_9_add_cast_1 = {LUT_Chunk_18_out1[15], LUT_Chunk_18_out1};
  assign Adder_S1_9_out1 = Adder_S1_9_add_cast + Adder_S1_9_add_cast_1;



  assign BitSlice_Chunk_19_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_19_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_19_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_19_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_19_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_19_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_19_out1 = LUT_Chunk_19_1[BitSlice_Chunk_19_out1];



  assign BitSlice_Chunk_20_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_20_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_20_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_20_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_20_out1 = LUT_Chunk_20_1[BitSlice_Chunk_20_out1];



  assign Adder_S1_10_add_cast = {LUT_Chunk_19_out1[15], LUT_Chunk_19_out1};
  assign Adder_S1_10_add_cast_1 = {LUT_Chunk_20_out1[15], LUT_Chunk_20_out1};
  assign Adder_S1_10_out1 = Adder_S1_10_add_cast + Adder_S1_10_add_cast_1;



  assign Adder_S2_5_add_cast = {Adder_S1_9_out1[16], Adder_S1_9_out1};
  assign Adder_S2_5_add_cast_1 = {Adder_S1_10_out1[16], Adder_S1_10_out1};
  assign Adder_S2_5_out1 = Adder_S2_5_add_cast + Adder_S2_5_add_cast_1;



  assign BitSlice_Chunk_21_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_21_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_21_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_21_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_21_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_21_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_21_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_21_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_21_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_21_out1 = LUT_Chunk_21_1[BitSlice_Chunk_21_out1];



  assign BitSlice_Chunk_22_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_22_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_22_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_22_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_22_out1 = LUT_Chunk_22_1[BitSlice_Chunk_22_out1];



  assign Adder_S1_11_add_cast = {LUT_Chunk_21_out1[15], LUT_Chunk_21_out1};
  assign Adder_S1_11_add_cast_1 = {LUT_Chunk_22_out1[15], LUT_Chunk_22_out1};
  assign Adder_S1_11_out1 = Adder_S1_11_add_cast + Adder_S1_11_add_cast_1;



  assign BitSlice_Chunk_23_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_23_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_23_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_23_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_23_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_23_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_23_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_23_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_23_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_23_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_23_out1 = LUT_Chunk_23_1[BitSlice_Chunk_23_out1];



  assign BitSlice_Chunk_24_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_24_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_24_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_24_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_24_out1 = LUT_Chunk_24_1[BitSlice_Chunk_24_out1];



  assign Adder_S1_12_add_cast = {LUT_Chunk_23_out1[15], LUT_Chunk_23_out1};
  assign Adder_S1_12_add_cast_1 = {LUT_Chunk_24_out1[15], LUT_Chunk_24_out1};
  assign Adder_S1_12_out1 = Adder_S1_12_add_cast + Adder_S1_12_add_cast_1;



  assign Adder_S2_6_add_cast = {Adder_S1_11_out1[16], Adder_S1_11_out1};
  assign Adder_S2_6_add_cast_1 = {Adder_S1_12_out1[16], Adder_S1_12_out1};
  assign Adder_S2_6_out1 = Adder_S2_6_add_cast + Adder_S2_6_add_cast_1;



  assign Adder_S3_3_add_cast = {Adder_S2_5_out1[17], Adder_S2_5_out1};
  assign Adder_S3_3_add_cast_1 = {Adder_S2_6_out1[17], Adder_S2_6_out1};
  assign Adder_S3_3_out1 = Adder_S3_3_add_cast + Adder_S3_3_add_cast_1;



  assign BitSlice_Chunk_25_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_25_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_25_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_25_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_25_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_25_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_25_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_25_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_25_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_25_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_25_out1 = LUT_Chunk_25_1[BitSlice_Chunk_25_out1];



  assign BitSlice_Chunk_26_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_26_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_26_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_26_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_26_out1 = LUT_Chunk_26_1[BitSlice_Chunk_26_out1];



  assign Adder_S1_13_add_cast = {LUT_Chunk_25_out1[15], LUT_Chunk_25_out1};
  assign Adder_S1_13_add_cast_1 = {LUT_Chunk_26_out1[15], LUT_Chunk_26_out1};
  assign Adder_S1_13_out1 = Adder_S1_13_add_cast + Adder_S1_13_add_cast_1;



  assign BitSlice_Chunk_27_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_27_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_27_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_27_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_27_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_27_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_27_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_27_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_27_out1 = LUT_Chunk_27_1[BitSlice_Chunk_27_out1];



  assign BitSlice_Chunk_28_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_28_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_28_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[2] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[5] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[7] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[9] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[11] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[13] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_28_1[15] = 16'sb0111111111111111;
  assign LUT_Chunk_28_out1 = LUT_Chunk_28_1[BitSlice_Chunk_28_out1];



  assign Adder_S1_14_add_cast = {LUT_Chunk_27_out1[15], LUT_Chunk_27_out1};
  assign Adder_S1_14_add_cast_1 = {LUT_Chunk_28_out1[15], LUT_Chunk_28_out1};
  assign Adder_S1_14_out1 = Adder_S1_14_add_cast + Adder_S1_14_add_cast_1;



  assign Adder_S2_7_add_cast = {Adder_S1_13_out1[16], Adder_S1_13_out1};
  assign Adder_S2_7_add_cast_1 = {Adder_S1_14_out1[16], Adder_S1_14_out1};
  assign Adder_S2_7_out1 = Adder_S2_7_add_cast + Adder_S2_7_add_cast_1;



  assign BitSlice_Chunk_29_out1 = Delay_1_out1[3:0];



  assign LUT_Chunk_29_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_29_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_29_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[3] = 16'sb0111111111111111;
  assign LUT_Chunk_29_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_29_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_29_out1 = LUT_Chunk_29_1[BitSlice_Chunk_29_out1];



  assign BitSlice_Chunk_30_out1 = Delay_2_out1[3:0];



  assign LUT_Chunk_30_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_30_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[4] = 16'sb0111111111111111;
  assign LUT_Chunk_30_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[6] = 16'sb0111111111111111;
  assign LUT_Chunk_30_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[8] = 16'sb0111111111111111;
  assign LUT_Chunk_30_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[10] = 16'sb0111111111111111;
  assign LUT_Chunk_30_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[12] = 16'sb0111111111111111;
  assign LUT_Chunk_30_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_30_1[14] = 16'sb0111111111111111;
  assign LUT_Chunk_30_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_30_out1 = LUT_Chunk_30_1[BitSlice_Chunk_30_out1];



  assign Adder_S1_15_add_cast = {LUT_Chunk_29_out1[15], LUT_Chunk_29_out1};
  assign Adder_S1_15_add_cast_1 = {LUT_Chunk_30_out1[15], LUT_Chunk_30_out1};
  assign Adder_S1_15_out1 = Adder_S1_15_add_cast + Adder_S1_15_add_cast_1;



  assign BitSlice_Chunk_31_out1 = Delay_3_out1[3:0];



  assign LUT_Chunk_31_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_31_1[1] = 16'sb0111111111111111;
  assign LUT_Chunk_31_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_31_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_31_out1 = LUT_Chunk_31_1[BitSlice_Chunk_31_out1];



  assign BitSlice_Chunk_32_out1 = Delay_4_out1[3:0];



  assign LUT_Chunk_32_1[0] = 16'sb0000000000000000;
  assign LUT_Chunk_32_1[1] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[2] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[3] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[4] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[5] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[6] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[7] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[8] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[9] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[10] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[11] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[12] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[13] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[14] = 16'sb1000000000000000;
  assign LUT_Chunk_32_1[15] = 16'sb1000000000000000;
  assign LUT_Chunk_32_out1 = LUT_Chunk_32_1[BitSlice_Chunk_32_out1];



  assign Adder_S1_16_add_cast = {LUT_Chunk_31_out1[15], LUT_Chunk_31_out1};
  assign Adder_S1_16_add_cast_1 = {LUT_Chunk_32_out1[15], LUT_Chunk_32_out1};
  assign Adder_S1_16_out1 = Adder_S1_16_add_cast + Adder_S1_16_add_cast_1;



  assign Adder_S2_8_add_cast = {Adder_S1_15_out1[16], Adder_S1_15_out1};
  assign Adder_S2_8_add_cast_1 = {Adder_S1_16_out1[16], Adder_S1_16_out1};
  assign Adder_S2_8_out1 = Adder_S2_8_add_cast + Adder_S2_8_add_cast_1;



  assign Adder_S3_4_add_cast = {Adder_S2_7_out1[17], Adder_S2_7_out1};
  assign Adder_S3_4_add_cast_1 = {Adder_S2_8_out1[17], Adder_S2_8_out1};
  assign Adder_S3_4_out1 = Adder_S3_4_add_cast + Adder_S3_4_add_cast_1;



  assign Adder_S4_2_add_cast = {Adder_S3_3_out1[18], Adder_S3_3_out1};
  assign Adder_S4_2_add_cast_1 = {Adder_S3_4_out1[18], Adder_S3_4_out1};
  assign Adder_S4_2_out1 = Adder_S4_2_add_cast + Adder_S4_2_add_cast_1;



  assign Adder_S5_1_add_cast = {Adder_S4_1_out1[19], Adder_S4_1_out1};
  assign Adder_S5_1_add_cast_1 = {Adder_S4_2_out1[19], Adder_S4_2_out1};
  assign Adder_S5_1_out1 = Adder_S5_1_add_cast + Adder_S5_1_add_cast_1;



  assign ConstZero_S5_2_out1 = 16'sb0000000000000000;



  assign Adder_S5_2_add_cast = {Adder_S4_3_out1[19], Adder_S4_3_out1};
  assign Adder_S5_2_add_cast_1 = {{5{ConstZero_S5_2_out1[15]}}, ConstZero_S5_2_out1};
  assign Adder_S5_2_out1 = Adder_S5_2_add_cast + Adder_S5_2_add_cast_1;



  assign Adder_S6_1_add_cast = {Adder_S5_1_out1[20], Adder_S5_1_out1};
  assign Adder_S6_1_add_cast_1 = {Adder_S5_2_out1[20], Adder_S5_2_out1};
  assign Adder_S6_1_out1 = Adder_S6_1_add_cast + Adder_S6_1_add_cast_1;



  assign Shift_Arithmetic_Scale_out1 = Adder_S6_1_out1 >>> 8'd2;



  assign Out1 = Shift_Arithmetic_Scale_out1;

  assign ce_out = clk_enable;

endmodule  // da_fir_bandpass

