// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\Custom_DA_FIR3\da_fir_bandpass_tb.v
// Created: 2026-07-04 18:59:10
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: da_fir_bandpass_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module da_fir_bandpass_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire signed [15:0] rawData_In1;  // sfix16_En15
  wire Out1_done;  // ufix1
  wire rdEnb;
  wire Out1_done_enb;  // ufix1
  reg [5:0] Out1_addr;  // ufix6
  wire Out1_active;  // ufix1
  reg signed [15:0] holdData_In1;  // sfix16_En15
  reg signed [15:0] In1_offset;  // sfix16_En15
  wire signed [15:0] In1_1;  // sfix16_En15
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire resetn;
  wire tb_enb;
  reg  tb_enb_delay;
  wire ce_out;
  wire signed [21:0] Out1;  // sfix22_En15
  wire Out1_enb;  // ufix1
  wire Out1_lastAddr;  // ufix1
  wire signed [21:0] Out1_expected_1;  // sfix22_En15
  wire signed [21:0] Out1_ref;  // sfix22_En15
  reg  Out1_testFailure;  // ufix1
  wire testFailure;  // ufix1


  // Data source for In1
  assign rawData_In1 = 16'sb0000000000000000;



  assign Out1_done_enb = Out1_done & rdEnb;



  assign Out1_active = Out1_addr != 6'b110010;



  // holdData reg for In1
  always @(posedge clk or posedge reset)
    begin : stimuli_In1
      if (reset) begin
        holdData_In1 <= 16'bx;
      end
      else begin
        holdData_In1 <= rawData_In1;
      end
    end

  always @(rawData_In1 or rdEnb)
    begin : stimuli_In1_1
      if (rdEnb == 1'b0) begin
        In1_offset <= holdData_In1;
      end
      else begin
        In1_offset <= rawData_In1;
      end
    end

  assign #2 In1_1 = In1_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  da_fir_bandpass u_da_fir_bandpass (.clk(clk),
                                     .reset(reset),
                                     .clk_enable(clk_enable),
                                     .In1(In1_1),  // sfix16_En15
                                     .ce_out(ce_out),
                                     .Out1(Out1)  // sfix22_En15
                                     );

  assign Out1_enb = ce_out & Out1_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 50
  always @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        Out1_addr <= 6'b000000;
      end
      else begin
        if (Out1_enb) begin
          if (Out1_addr >= 6'b110010) begin
            Out1_addr <= 6'b000000;
          end
          else begin
            Out1_addr <= Out1_addr + 6'b000001;
          end
        end
      end
    end



  assign Out1_lastAddr = Out1_addr >= 6'b110010;



  assign Out1_done = Out1_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (Out1_done_enb) begin
          check1_done <= Out1_done;
        end
      end
    end

  // Data source for Out1_expected
  assign Out1_expected_1 = 22'sb0000000000000000000000;



  assign Out1_ref = Out1_expected_1;

  always @(posedge clk or posedge reset)
    begin : Out1_checker
      if (reset == 1'b1) begin
        Out1_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Out1 !== Out1_ref) begin
          Out1_testFailure <= 1'b1;
          $display("ERROR in Out1 at time %t : Expected '%h' Actual '%h'", $time, Out1_ref, Out1);
        end
      end
    end

  assign testFailure = Out1_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // da_fir_bandpass_tb

